name: Create Release Tag

on:
  pull_request:
    types:
      - closed

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
        git config user.name "${{ secrets.GITHUB_ACTOR }}"
        git fetch --tags

    - name: Create Release Tag
      run: |
        # Get the PR title and replace spaces with underscores
        PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | tr -d '[:space:]' | tr ' ' '_')

        # Create a new tag using the PR title
        git tag -a $PR_TITLE -m "Release $PR_TITLE"

        # Push the tag to the repository
        git push origin $PR_TITLE

    - name: Create Release File
      run: |
        # Create release.txt file
        echo "Release for ${{ github.event.pull_request.title }}" > release.txt

        # Commit the release.txt file
        git add release.txt
        git commit -m "Add release.txt for ${{ github.event.pull_request.title }}"
        git push origin main
