name: Tag and Release

on:
  push:
    branches:
      - master

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Get PR number
      id: pr
      run: echo "::set-output name=pr_number::$(echo $GITHUB_REF | awk -F'/' '{print $3}')"

    - name: Create and push tags
      run: |
        tag="pr-${{ steps.pr.outputs.pr_number }}"
        git tag "$tag" -m "Tag for PR #${{ steps.pr.outputs.pr_number }}"
        git push origin "$tag"

    - name: Generate kustomize outputs for overlays
      run: |
        for overlay in overlays/*; do
          overlay_name=$(basename "$overlay")
          output_folder="testPR/$overlay_name"
          mkdir -p "$output_folder"
          kustomize build "$overlay" > "$output_folder/kustomize_output.yaml"
          git add "$output_folder/kustomize_output.yaml"
        done

    - name: Display staged changes
      run: git status

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update kustomize outputs for overlays" || true  # Ignore if there are no changes
        git push origin HEAD:main  # Change 'main' to your branch name
